// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20260112073451_Added phine number and address to user.")]
    partial class Addedphinenumberandaddresstouser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "b8dd6cb1-d02c-440d-828b-3056017e4390",
                            Email = "email@mail.ru",
                            FirstName = "John",
                            ImageUrl = "/koala.webp",
                            LastName = "Black",
                            PasswordHash = "System.Byte[]",
                            PhoneNumber = "+375299998493",
                            Username = "JoeBlack"
                        },
                        new
                        {
                            Id = "cd244cd6-239f-49c7-9532-7dbd95e4a156",
                            Email = "myEmail@mail.ru",
                            FirstName = "Kirill",
                            ImageUrl = "/koala.webp",
                            LastName = "Bush",
                            PasswordHash = "System.Byte[]",
                            PhoneNumber = "+375299998493",
                            Username = "Baiden"
                        });
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.OwnsOne("Entities.Models.Address", "Address", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("State")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.HasData(
                                new
                                {
                                    UserId = "b8dd6cb1-d02c-440d-828b-3056017e4390",
                                    City = "Minsk",
                                    Country = "Belarus",
                                    PostalCode = "222435",
                                    State = "No state",
                                    Street = "Kastrychnickaya"
                                });
                        });

                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
