// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20260111101819_Added image url for users profile photo.")]
    partial class Addedimageurlforusersprofilephoto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "99029d4a-874e-43d1-9117-41fddb992283",
                            Email = "email@mail.ru",
                            FirstName = "John",
                            ImageUrl = "/koala.webp",
                            LastName = "Black",
                            PasswordHash = "System.Byte[]",
                            Username = "JoeBlack"
                        },
                        new
                        {
                            Id = "52df3dcf-3a4a-4f4b-b1c0-2f4c00caf4de",
                            Email = "myEmail@mail.ru",
                            FirstName = "Kirill",
                            ImageUrl = "/koala.webp",
                            LastName = "Bush",
                            PasswordHash = "System.Byte[]",
                            Username = "Baiden"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
